# Generated by Django 5.1.1 on 2024-09-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0002_alter_donor_options_alter_fundraiser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
